### ISSUE TITLE
TTGO version gets stuck within EV_TXPEND forever

### ISSUE THREAD

**Issue by jdgarcia99** [JackGruber/ESP32-LMIC-DeepSleep-example#2]
Hi,

I'm using Stack v3 and using your code to deep sleep an TTGO OLED LoRa v1.

The problem is that first deep sleep works well, but next iteration the program gets into an infinite loop with the status EV_TXPEND.

I attach output to console (I added some code to see how program is passing through different events):

rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
Initializing OLED Screen
Starting DeepSleep test
Packet queued
10411: EV_JOINING
Cannot sleep
Cannot sleep
Cannot sleep
223351: EV_TXSTART
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
544617: EV_JOINED
netid: 19
devaddr: 260B6122
artKey: A59146F1F92790831D3B717F186932
nwkKey: 6AD6D85440C7577ABE5C766F21D4DC96
544878: EV_TXSTART
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
864847: EV_TXCOMPLETE (includes waiting for RX windows)
Cannot sleep
Cannot sleep
961840: EV_TXSTART
Go DeepSleep
ets Jul 29 2019 12:21:46

rst:0x5 (DEEPSLEEP_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
Initializing OLED Screen
Starting DeepSleep test
LMIC loaded from RTC
OP_TXRXPEND, not sending
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep
Cannot sleep

**Comment by JackGruber** [comment]
Sometimes the Board needs after a flash a reset to work correctly, have you tried this?

**Comment by daeynasvistas** [comment]
Same problem.. same board
