### ISSUE TITLE
OP_TXRXPEND pending

### ISSUE THREAD

**Issue by JackGruber** [JackGruber/ESP32-LMIC-DeepSleep-example#3]
Hi all,

I'm using an EZSBC ESP32 Dev board with separate rfm95w (EU868) and having the same problem when using TTN V3 credeńtials. Problem starts when TTN sends an unconfirmed downlink LinkADReq after a regular unconfirmed uplink by the node (FCnt 19 in the attachment) and this gets answered with an LinkADRAns. After this, the node is starting it's deepsleep , and the value for LMIC.opmode that is written to RTC seems to refer to a busy mode. After waking up, the node continues with LMIC.opmode: OP_TXRXPEND OP_NEXTCHNL  which causes the system to be unable to send data to TTN
See Attachments.

@JackGruber : can we solve this issue by checking the LMIC.opmode status before writing it to RTC and -if necessary- correct it. Do we need the value for LMIC.opmode saved to RTC anyway?

Thanks a lot!

BR Marc
[Error ESP32 DeepSleep TTNV3.txt](https://github.com/JackGruber/ESP32-LMIC-DeepSleep-example/files/6742266/Error.ESP32.DeepSleep.TTNV3.txt)
![Screenshot_2021-06-29 RAK7258 - LoRa Packet Logger - LuCI](https://user-images.githubusercontent.com/86732923/123991416-fd3a2700-d9ca-11eb-8822-cd20df9f8cac.png)

_Originally posted by @MarcESP32 in https://github.com/JackGruber/ESP32-LMIC-DeepSleep-example/issues/1#issuecomment-871524131_

**Comment by JackGruber** [comment]
@MarcESP32 you can try the fix 0ea9de3

**Comment by MarcESP32** [comment]
fix tested. Issue solved.
Thanks a lot.
